name: Build LaTeX document

# Controls when the action will run. 
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        
      - name: Compile main LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: relazione 
          root_file: main.tex

      - name: Check if PDF was created
        run: |
          ls -la
          ls -la relazione
          if [ -f "main.pdf" ]; then
            echo "PDF generated successfully."
          else
            echo "PDF generation failed." >&2
            exit 1
          fi